kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: main-project
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'